### ISSUE TITLE
[BUG] Semester date can't be retrieved automatically anymore

### ISSUE THREAD

**Issue by yxliang01** [nuclearpidgeon/UoM-Timetable-to-iCal#11]
The message says "Could not find any dates on the UoM principle dates pages. Please enter dates manually below"

Thanks!

**Comment by nuclearpidgeon** [comment]
Hey Xiao, thanks for reporting this.

The Unimelb principle dates page seems to change structure every year
(worst 'API' ever), so I'll probably have to update my code that scrapes
the dates again.

I think you can still use the manual form fields as a fallback in the mean
time. However the semester break probably won't work properly yet either,
from memory it's still hard coded for last year.

I'm planning to spend some more time on this over the next few weeks seeing
as semester is starting up again, so I'll let you know if I get around to
fixing this :).

**Comment by nuclearpidgeon** [comment]
Hey Xiao, I just posted a new version (v1.1.4) of the extension that will hopefully work properly with the new dates page. Can you please test it if you have a spare second to see if it works? I don't have a live unimelb timetable to test against anymore so it would be great to get confirmation that it still works.

BTW I discovered today that the fixes I had originally written in 2016 that made the extension work with the new dates page never got published 😑  - a new version was sitting as a draft in the extension store, but I had forgotten to actually publish it!!

However I also discovered that this version was hard-coded to 2016 by accident, and may have had a permissions issue with accessing the new dates page, so I've fixed those things and published them as that new v1.1.4 version.

**Comment by yxliang01** [comment]
Thanks for your effort. Due to assignments, projects, I will test it this week. :)

**Comment by yxliang01** [comment]
Hello @nuclearpidgeon , I am happy to tell you that the date fetching works! :)

**Comment by nuclearpidgeon** [comment]
Thanks so much for the feedback! 🙌  great to hear that it works

**Comment by yxliang01** [comment]
Also, thank you for your contribution to unimlb students :)
