### ISSUE TITLE
Future Semester support

### ISSUE THREAD

**Issue by nuclearpidgeon** [nuclearpidgeon/UoM-Timetable-to-iCal#3]
The extension is currently hard-coded to support Semester 2 only.

**Comment by nuclearpidgeon** [comment]
as of 059a619936df2941db680d930ca139bc6ddad924 (1.1.0) Semester dates are auto-fetched from the unimelb principal dates calendar. Next step is to also support fetching or at least entering the break dates - this needs some updating though due to the inclusion of Easter Friday in semester 1

**Comment by lberezy** [comment]
The principle dates page has not been updated from the [2015 version](http://www.unimelb.edu.au/unisec/PDates/) yet, but there is a link to a [2016-2018 page](http://www.unimelb.edu.au/unisec/PDates/acadcale.html).

Thoughts on how to deal with this?

**Comment by nuclearpidgeon** [comment]
Hahaha I knew that as soon as I hard-coded support for that one page, that they would change the way the dates are presented.

It should still be possible to use jQuery to match on the "Academic Calendar for 20xx" elements, then find the first <table> after each one to grab the dates - I'll just need to alter the code that searches for dates in my extension - somewhere around [here](https://github.com/nuclearpidgeon/UoM-Timetable-to-iCal/blob/1.1.1/extension/popup.js#L96).

**Comment by nuclearpidgeon** [comment]
* Future semesters now kinda work so long as the UoM date page doesn't keep changing (this is a separate issue however.)
* Support for handling breaks is still hard-coded but I have created a new issue for this: #8
